from curses import *
RED = COLOR_RED
BLUE = COLOR_BLUE
CYAN = COLOR_CYAN
GREEN = COLOR_GREEN
WHITE = COLOR_WHITE
BLACK = COLOR_BLACK
YELLOW = COLOR_YELLOW
MAGENTA = COLOR_MAGENTA
GREY = 8


BRIGHT_GREEN = 10
BRIGHT_RED = 12
BRIGHT_BLUE = 9
BRIGHT_CYAN = 11
BRIGHT_WHITE = 15
BRIGHT_YELLOW = 14
BRIGHT_MAGENTA = 13

BACKGROUND = BLACK